# Generated by Django 5.2.7 on 2025-10-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="telegram_username",
            field=models.CharField(blank=True, max_length=100, verbose_name="Telegram username"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="telegram_chat_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, unique=True, verbose_name="Telegram Chat ID"
            ),
        ),
    ]
